sap.ui.define([], function () {
	"use strict";

	return {
		ABAP_TRUE: "X",
		PACK_STATUS_IN_PROCESS: "p",
		PICK_STATUS_COMPLETE: "1",
		INIT_TAB_TITLE: " ",
		SHIP_TYPE_HU: 1,
		SOURCE_TYPE_ODO: "3",
		SERIAL_NUMBER_DISABLE: "",
		SN_DOC_LEVEL_PROFILE_A: "A",
		SN_DOC_LEVEL_PROFILE_B: "B",
		SERIAL_NUMBER_STOCK_LEVEL: "C",
		ADVANCED_MODE: "advanced",
		BASIC_MODE: "basic",
		INTERNAL_MODE: "internl",
		ERROR: "E",
		INFO: "I",
		WARNING: "W",
		ADVANCED_ROUTE_NAME: "main",
		BASIC_ROUTE_NAME: "simple",
		DEFAULT_ROUTE_NAME: "default",
		INTERNAL_ROUTE_NAME: "internal",
		ITEM_MODEL_NAME: "itemModel",
		COLUM_SETTING_MODEL_NAME: "columnModel",
		VIEW_SOURCE: "source",
		VIEW_SHIP: "ship",
		WORKCENTER_KEY: "WorkCenter",
		WORKCENTER_DESC: "Desc",
		STORAGEBIN_KEY: "StorageBin",
		STORAGE_TYE: "StorageType",
		UOM_TYPE: {
			ALTER: "AlterUnit",
			BASE: "BaseUnit"
		},
		ACCESS_CODE: {
			"PACK_ITEM": "PACK_ITEM",
			"PACK_ALL": "PACK_ALL",
			"CLOSE_HU": "CLOSE_HU",
			"CREATE_HU": "CREATE_HU"
		},
		EXCCODE: {
			"DIFF": "DIFF",
			"EXPA": "EXPA"
		},
		EVENT_BUS: {
			CHANNELS: {
				USER_SETTING: "USER SETTING",
				UNPACK: "UNPACK",
				PACK: "PACK",
				EXCEPTION_LIST: "EXCEPTION LIST",
				EXCEPTION_ENABLE: "EXCEPTION BUTTONS ENABLE",
				PACKALL_ENABLE: "PACKALL BUTTON ENABLE",
				ROUTE_MATCHED: "ROUTE_MATCHED"
			},
			EVENTS: {
				CHANGED: "CHANGED",
				SUCCESS: "SUCCESS",
				ERROR: "ERROR",
				WAREHOUSE_CHANGED: "WAREHOUSE_CHAGNED"
			}
		},
		ERRORS: {
			"NO_NETWORK": "NO_NETWORK",
			"INTERRUPT_WITH_NO_ACTION": "INTERRUPT_WITH_NO_ACTION",
			"INVALID_INPUT": "INVALID_INPUT",
			"PACK_UNPACK_ERROR": "/SCWM/OUTB_PACK-001",
			"HU_NOT_EXIST": "/SCWM/HU_WM-015",
			"DIFF_CONSOLIDATION_GROUP": "/SCWM/HU_WM-013",
			"NO_PROCESSOR_FOR_USER": "/SCWM/L3-112",
			"PACK_QUANTITY_ZERO": "/SCWM/HUGENERAL-083",
			"EXCEED_MAX_VOLUME": "/SCWM/HUGENERAL-064",
			"NEGATIVE_PACKING_QUANTITY": "/SCWM/HUFUNCTIONS-605",
			"CREATE_HU_DUPLICATE": "/SCWM/HU_WM-017",
			"BIN_NOT_EXIST": "BIN_NOT_EXIST",
			"BIN_NOT_IN_PACKING_STATION": "BIN_NOT_IN_PACKING_STATION",
			"SCAN_SHIPHU_IN_SOURCE_INPUT": "SCAN_SHIPHU_IN_SOURCE_INPUT",
			"SCAN_SOURCEHU_IN_SHIP_INPUT": "SCAN_SOURCEHU_IN_SHIP_INPUT",
			"SOURCE_NO_ITEM": "SOURCE_NO_ITEM",
			"PRODUCT_NOT_IN_SOURCE": "PRODUCT_NOT_IN_SOURCE",
			"MAX_WEIGHT_FOR_HU_EXCEED": "/SCWM/HUGENERAL-065",
			"PACK_OUTBOUND_CAN_NOT_BE_SET": "/SCWM/HU_WM-006",
			"SHIP_HU_CREATED_INTERNALLY": "/SCWM/HU_WM-041",
			"HU_NOT_IN_WORK_CENTER": "/SCWM/OUTB_PACK-008",
			"COULD_NOT_DETERMINE_BIN": "/SCWM/L3-008",
			"CHANGE_ID_DUPLICATE": "/SCWM/OUTB_PACK-017",
			"CHANGE_MATERIAL_EXCEED_MAX": "/SCWM/OUTB_PACK-018",
			"INITIAL_CAN_NOT_READ_HUS": "/SCWM/HUGENERAL-157",
			"EXECUTE_ORD_REDUCTION_FAILED": "/SCWM/OUTB_PACK-014",
			"HU_ASSIGNED_FAILED": "/SCWM/HU_WM-043",
			"STORAGE_BIN_NOT_IN_WAREHOUSE": "/SCWM/WM_SEL-074",
			"NOT_SUPPORT_SN_BATCH": "NOT_SUPPORT_SN_BATCH",
			"NOT_SUPPORT_STOCK_ID_SPLIT": "NOT_SUPPORT_STOCK_ID_SPLIT",
			"NO_ENOUGH_QUANTITY_APPLIED": "NO_ENOUGH_QUANTITY_APPLIED",
			"UPDATE_DB_ERROR": "/SCWM/UI_PACKING-157",
			"DELETE_HU_WITH_WT": "/SCWM/UI_PACKING-153",
			"INTERVAL_HU_ID_NOT_DEFINED": "/SCWM/HU_WM-044",
			"COULD_NOT_FIND_HU_ITEM": "/SCWM/OUTB_PACK-005",
			"DOCUMENT_LOCKED": "/SCDL/DL_DBAL_DB-002",
			"HU_OR_BIN_NOT_IN_WAREHOUSE": "/SCWM/OUTB_PACK-020",
			"PACK_WITH_NEGATIVE_QUANTITY": "/SCWM/OUTB_PACK-016",
			"PRODUCT_WITH_DIFF_CONS_GROUP": "PRODUCT_WITH_DIFF_CONS_GROUP",
			"SHIP_HU_NOT_IN_WORK_CENTER": "/SCWM/OUTB_PACK-021",
			"REQUIRED_DATA_NO_STOCK": "/SCWM/L3-104",
			"NO_MATERIAL": "NO_MATERIAL",
			"HU_PROCESSED_BY_OTHER": "/SCWM/HU_WM-042",
			"NO_PACKAGING_MATERIAL_SELECTED": "NO_PACKAGING_MATERIAL_SELECTED",
			"SHIP_HU_ALREADY_CLOSED": "SHIP_HU_ALREADY_CLOSED",
			"NO_FAVORITE_MATERIAL":"NO_FAVORITE_MATERIAL"
		},
		TAB: {
			"ADVANCED": "scm.ewm.PackingPOC.view.TabContent",
			"BASIC": "scm.ewm.PackingPOC.view.SimpleTabContent"
		},
		ID: {
			"SOURCE_INPUT": "source-hu-input",
			"PRODUCT_INPUT": "product-input",
			"SHIP_INPUT": "shipping-hu-input",
			"CREATE_SHIP_INPUT": "create-ship-hu-input",
			"CHANGE_SHIP_INPUT": "change-hu-id-input",
			"ERROR_MATERIAL_STRIP": "error-material-strip"
		},
		OPERATOR: {
			"PLUS": "PLUS",
			"MINUS": "MINUS"
		},
		PACK_MODE: {
			"OUTBOUND": 1,
			"INTERNAL": 2
		}
	};
});